# Generated by Django 4.0.1 on 2022-01-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('game', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
