# Generated by Django 4.0.2 on 2022-02-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event',
        ),
        migrations.RemoveField(
            model_name='events',
            name='game',
        ),
        migrations.RemoveField(
            model_name='events',
            name='place',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
        migrations.AddField(
            model_name='events',
            name='student_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='events',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
