# Generated by Django 4.0.4 on 2022-07-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_date_remove_events_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('img', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
